// Official List of all 86 Barangays in Butuan City, Agusan del Norte
export const BUTUAN_BARANGAYS = [
  'Pianing',
  'Anticala',
  'Agao Poblacion',
  'Agusan Pequeño',
  'Ambago',
  'Amparo',
  'Ampayon',
  'Antongalon',
  'Aupagan',
  'Baan Km 3',
  'Baan Riverside',
  'Babag',
  'Bading',
  'Banza',
  'Baobaoan',
  'Basag',
  'Bayanihan',
  'Bilay',
  'Bit-os',
  'Bitan-agan',
  'Bobon',
  'Bonbon',
  'Bugabus',
  'Buhangin',
  'Cabcabon',
  'Camayahan',
  'Dagohoy',
  'Dankias',
  'De Oro',
  'Diego Silang',
  'Doongan',
  'Dumalagan',
  'Golden Ribbon',
  'Holy Redeemer',
  'Humabon',
  'Imadejas',
  'Kinamlutan',
  'Lapu-lapu',
  'Lemon',
  'Libertad',
  'Limaha',
  'Los Angeles',
  'Lumbocan',
  'Maguinda',
  'Mahay',
  'Mahogany',
  'Maibu',
  'Mandamo',
  'Manila de Bugabus',
  'Maon',
  'Masao',
  'Maug',
  'New Society Village',
  'Nong-nong',
  'Obrero',
  'Ong Yiu',
  'Pagatpatan',
  'Pangabugan',
  'Pigdaulan',
  'Pinamanculan',
  'Poblacion',
  'Port Poyohon',
  'Rajah Soliman',
  'Salvacion',
  'San Ignacio',
  'San Mateo',
  'San Vicente',
  'Santa Cruz',
  'Santa Ines',
  'Santo Niño',
  'Sikatuna',
  'Silongan',
  'Sumilihon',
  'Tagabaca',
  'Taguibo',
  'Taligaman',
  'Tandang Sora',
  'Tiniwisan',
  'Tungao',
  'Urduja',
  'Victoria',
  'Villa Kananga'
] as const;

export type ButuanBarangay = typeof BUTUAN_BARANGAYS[number];
